version: '3.8'

services:
  tailer:
    #build: .
    image: tailer:0.0.5
    ports:
      - "30000:3000"
    volumes:
      - ./logs:/logs
    environment:
      - NODE_ENV=production

volumes:
  logs:
    driver: local

